// Package model defines the message and tool-call protocol used internally by Atlas.
package model

import "strings"

// Role represents the role of a chat message.
type Role string

const (
	// RoleSystem represents a system-level instruction.
	RoleSystem Role = "system"
	// RoleUser represents user input.
	RoleUser Role = "user"
	// RoleAssistant represents model output.
	RoleAssistant Role = "assistant"
	// RoleTool represents a tool-call result.
	RoleTool Role = "tool"
)

// ToolCall represents a single local Atlas tool the model requests to execute.
type ToolCall struct {
	// ID is generated by the provider; the matching tool result must carry the same ID.
	ID   string
	Name string
	// Arguments is the raw JSON object string produced by the model.
	// The agent matches the tool name, then the tool implementation parses the arguments.
	Arguments string
}

// TodoStatus represents the execution status of a single todo item.
type TodoStatus string

const (
	// TodoStatusPending means the task has not started.
	TodoStatusPending TodoStatus = "pending"
	// TodoStatusInProgress means the task is currently executing.
	TodoStatusInProgress TodoStatus = "in_progress"
	// TodoStatusCompleted means the task is finished.
	TodoStatusCompleted TodoStatus = "completed"
)

// TodoEntry describes a single task entry in a todo list.
type TodoEntry struct {
	Content string     `json:"content"`
	Status  TodoStatus `json:"status"`
}

// ToolMetadata holds UI-facing presentation data for a tool call.
type ToolMetadata struct {
	Todos       []TodoEntry `json:"todos,omitempty"`
	Error       bool        `json:"error,omitempty"`
	DirectShell bool        `json:"direct_shell,omitempty"`
}

// ContentPartType represents the modality type of a message content segment.
type ContentPartType string

const (
	// ContentPartText represents plain text content.
	ContentPartText ContentPartType = "text"
	// ContentPartImage represents inline image content.
	ContentPartImage ContentPartType = "image"
)

// ImageDetail represents the image resolution preference for model processing.
type ImageDetail string

const (
	// ImageDetailAuto lets the provider or model choose image resolution automatically.
	ImageDetailAuto ImageDetail = "auto"
	// ImageDetailLow represents low-resolution image input.
	ImageDetailLow ImageDetail = "low"
	// ImageDetailHigh represents high-resolution image input.
	ImageDetailHigh ImageDetail = "high"
)

// ContentPart describes a single text or image segment within a message.
type ContentPart struct {
	Type     ContentPartType `json:"type"`
	Text     string          `json:"text,omitempty"`
	MimeType string          `json:"mime_type,omitempty"`
	DataURL  string          `json:"data_url,omitempty"`
	URI      string          `json:"uri,omitempty"`
	Detail   ImageDetail     `json:"detail,omitempty"`
}

// ProviderItem stores an output item that must be replayed verbatim for a specific API format.
type ProviderItem struct {
	Type string `json:"type"`
	JSON string `json:"json"`
}

// ToolDefinition describes a function-calling tool definition sent to the model.
type ToolDefinition struct {
	Name        string
	Description string
	// Parameters is a JSON Schema object. The model package keeps it loosely typed
	// to avoid introducing an additional dependency for schema handling.
	Parameters map[string]any
}

// Message is the generic conversation unit used by the agent loop.
type Message struct {
	Role    Role
	Content string
	// Parts holds model-visible structured content; when empty, Content is used as a single text segment.
	Parts []ContentPart
	// ReasoningContent is only meaningful for assistant messages, used for provider chain-of-thought continuation.
	ReasoningContent string
	// ToolCalls is only meaningful for assistant messages.
	ToolCalls []ToolCall
	// ToolCallID is only meaningful for tool messages, used to associate the corresponding tool call.
	ToolCallID string
	// ToolMetadata is only meaningful for tool messages, used for structured result display in ACP and other clients.
	ToolMetadata ToolMetadata
	// Usage is only meaningful for assistant messages, recording token usage returned by the provider.
	Usage Usage
	// ProviderItems is only meaningful for assistant messages, used for provider-specific API state continuation.
	ProviderItems []ProviderItem
}

// TextMessage constructs a message containing a single text segment.
func TextMessage(role Role, content string) Message {
	return Message{
		Role:    role,
		Content: content,
		Parts:   []ContentPart{{Type: ContentPartText, Text: content}},
	}
}

// MessageParts returns the structured content of a message; legacy messages fall back to a text segment.
func MessageParts(msg Message) []ContentPart {
	if len(msg.Parts) > 0 {
		parts := make([]ContentPart, len(msg.Parts))
		copy(parts, msg.Parts)
		return parts
	}
	if msg.Content == "" {
		return nil
	}
	return []ContentPart{{Type: ContentPartText, Text: msg.Content}}
}

// TextFromParts extracts text from content segments for use in titles and compatibility fields.
func TextFromParts(parts []ContentPart) string {
	var text string
	for _, part := range parts {
		if part.Type != ContentPartText || part.Text == "" {
			continue
		}
		text = joinText(text, part.Text)
	}
	return text
}

func joinText(left, right string) string {
	if left == "" {
		return right
	}
	return left + "\n\n" + strings.TrimLeft(right, "\n")
}

// HasImagePart returns whether the message contains an image segment.
func HasImagePart(msg Message) bool {
	for _, part := range MessageParts(msg) {
		if part.Type == ContentPartImage {
			return true
		}
	}
	return false
}

// StopReason represents the reason a model step ended.
type StopReason string

const (
	// StopEndTurn means the model produced a terminal assistant reply for this turn.
	StopEndTurn StopReason = "end_turn"
	// StopToolUse means the model requested tool calls; the agent should execute them and continue.
	StopToolUse StopReason = "tool_use"
	// StopMaxTokens means the provider stopped due to the output token limit.
	StopMaxTokens StopReason = "max_tokens"
	// StopUnknown represents an unclassifiable provider finish reason.
	StopUnknown StopReason = "unknown"
)

// Usage records token usage returned by the provider.
type Usage struct {
	InputTokens           int
	OutputTokens          int
	TotalTokens           int
	CacheReadInputTokens  int
	CacheWriteInputTokens int
}

// StreamEventType represents the type of an incremental event in a provider stream.
type StreamEventType string

const (
	// StreamTextDelta represents an assistant text delta.
	StreamTextDelta StreamEventType = "text_delta"
	// StreamReasoningDelta represents an assistant chain-of-thought delta.
	StreamReasoningDelta StreamEventType = "reasoning_delta"
)

// StreamEvent is a real-time event produced by the provider during a model step.
type StreamEvent struct {
	Type  StreamEventType
	Delta string
}

// ResponseFormat describes the format requirement for provider-returned text.
type ResponseFormat string

const (
	// ResponseFormatJSONObject means the provider should return a JSON object.
	ResponseFormatJSONObject ResponseFormat = "json_object"
)

// ChatRequest is the complete generic input for a single model step.
type ChatRequest struct {
	System          string
	Messages        []Message
	Tools           []ToolDefinition
	SessionID       string
	MaxTokens       int
	Temperature     float64
	ReasoningEffort string
	ResponseFormat  ResponseFormat
}

// ChatResponse is the complete generic output for a single model step.
type ChatResponse struct {
	Content          string
	ReasoningContent string
	ToolCalls        []ToolCall
	StopReason       StopReason
	Usage            Usage
	ProviderItems    []ProviderItem
	// RawFinish preserves the provider's raw finish reason for debugging.
	RawFinish string
}
