import 'dart:convert';
import 'dart:io';

import 'package:dio/dio.dart';

/// Regenerates the offline models.dev snapshot from the provider package root.
Future<void> main(List<String> args) async {
  final http = Dio();
  try {
    final data = args.isEmpty
        ? (await http.get<Map<String, dynamic>>('https://models.dev/api.json'))
              .data!
        : jsonDecode(await File(args.single).readAsString())
              as Map<String, dynamic>;
    final selected = <String, Object?>{};
    for (final id in ['openai', 'anthropic']) {
      final provider = data[id] as Map<String, dynamic>;
      selected[id] = {
        'models': {
          for (final entry
              in (provider['models'] as Map<String, dynamic>).entries)
            if ((entry.value as Map)['tool_call'] == true)
              entry.key: {
                for (final field in [
                  'name',
                  'tool_call',
                  'status',
                  'type',
                  'limit',
                  'modalities',
                  'reasoning',
                  'reasoning_options',
                  'temperature',
                  'cost',
                ])
                  if ((entry.value as Map).containsKey(field))
                    field: (entry.value as Map)[field],
              },
        },
      };
    }
    final encoded = const JsonEncoder.withIndent('  ').convert(selected);
    if (encoded.contains("'''")) {
      throw const FormatException('Invalid snapshot delimiter');
    }
    await File('lib/src/catalog_snapshot.dart').writeAsString(
      '// Generated by tool/update_catalog.dart from https://models.dev/api.json.\n'
      '// models.dev data: MIT license; see THIRD_PARTY_NOTICES.md.\n'
      '/// Bundled provider metadata for offline startup.\n'
      "const bundledCatalogJson = r'''\n$encoded\n''';\n",
    );
  } finally {
    http.close();
  }
}
