// Generated by tool/update_catalog.dart from https://models.dev/api.json.
// models.dev data: MIT license; see THIRD_PARTY_NOTICES.md.
/// Bundled provider metadata for offline startup.
const bundledCatalogJson = r'''
{
  "openai": {
    "models": {
      "gpt-5.4": {
        "name": "GPT-5.4",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": true,
        "cost": {
          "input": 2.5,
          "output": 15,
          "cache_read": 0.25,
          "tiers": [
            {
              "input": 5,
              "output": 22.5,
              "cache_read": 0.5,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 5,
            "output": 22.5,
            "cache_read": 0.5
          }
        }
      },
      "gpt-5.4-pro": {
        "name": "GPT-5.4 Pro",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 30,
          "output": 180,
          "tiers": [
            {
              "input": 60,
              "output": 270,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 60,
            "output": 270
          }
        }
      },
      "gpt-5.5-pro": {
        "name": "GPT-5.5 Pro",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 30,
          "output": 180,
          "tiers": [
            {
              "input": 60,
              "output": 270,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 60,
            "output": 270
          }
        }
      },
      "gpt-5.4-nano": {
        "name": "GPT-5.4 nano",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": true,
        "cost": {
          "input": 0.2,
          "output": 1.25,
          "cache_read": 0.02
        }
      },
      "gpt-realtime-2.1": {
        "name": "GPT-Realtime-2.1",
        "tool_call": true,
        "limit": {
          "context": 128000,
          "input": 96000,
          "output": 32000
        },
        "modalities": {
          "input": [
            "text",
            "audio",
            "image"
          ],
          "output": [
            "text",
            "audio"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "minimal",
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 4,
          "output": 24,
          "cache_read": 0.4,
          "input_audio": 32,
          "output_audio": 64
        }
      },
      "gpt-4o-2024-05-13": {
        "name": "GPT-4o (2024-05-13)",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 5,
          "output": 15
        }
      },
      "gpt-4o": {
        "name": "GPT-4o",
        "tool_call": true,
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 2.5,
          "output": 10,
          "cache_read": 1.25
        }
      },
      "gpt-5-mini": {
        "name": "GPT-5 Mini",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "minimal",
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 0.25,
          "output": 2,
          "cache_read": 0.025
        }
      },
      "gpt-5.2-pro": {
        "name": "GPT-5.2 Pro",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 21,
          "output": 168
        }
      },
      "o4-mini": {
        "name": "o4-mini",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 1.1,
          "output": 4.4,
          "cache_read": 0.275
        }
      },
      "o3-mini": {
        "name": "o3-mini",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 1.1,
          "output": 4.4,
          "cache_read": 0.55
        }
      },
      "gpt-4": {
        "name": "GPT-4",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 8192,
          "output": 8192
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 30,
          "output": 60
        }
      },
      "gpt-5.3-codex": {
        "name": "GPT-5.3 Codex",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": true,
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        }
      },
      "gpt-4.1-nano": {
        "name": "GPT-4.1 nano",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 1047576,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 0.1,
          "output": 0.4,
          "cache_read": 0.025
        }
      },
      "gpt-5-nano": {
        "name": "GPT-5 Nano",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "minimal",
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 0.05,
          "output": 0.4,
          "cache_read": 0.005
        }
      },
      "gpt-5.6": {
        "name": "GPT-5.6",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 4,
          "output": 20,
          "cache_read": 0.4,
          "cache_write": 5,
          "tiers": [
            {
              "input": 8,
              "output": 30,
              "cache_read": 0.8,
              "cache_write": 10,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 8,
            "output": 30,
            "cache_read": 0.8,
            "cache_write": 10
          }
        }
      },
      "gpt-5.2-chat-latest": {
        "name": "GPT-5.2 Chat",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "medium"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        }
      },
      "o1": {
        "name": "o1",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 15,
          "output": 60,
          "cache_read": 7.5
        }
      },
      "gpt-5-pro": {
        "name": "GPT-5 Pro",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 272000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 15,
          "output": 120
        }
      },
      "gpt-5.3-codex-spark": {
        "name": "GPT-5.3 Codex Spark",
        "tool_call": true,
        "limit": {
          "context": 128000,
          "input": 100000,
          "output": 32000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        }
      },
      "gpt-6.1-sol": {
        "name": "GPT-6.1 Sol",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 2,
          "output": 10,
          "cache_read": 0.1,
          "cache_write": 2.5,
          "tiers": [
            {
              "input": 4,
              "output": 15,
              "cache_read": 0.2,
              "cache_write": 5,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 4,
            "output": 15,
            "cache_read": 0.2,
            "cache_write": 5
          }
        }
      },
      "gpt-4o-2024-08-06": {
        "name": "GPT-4o (2024-08-06)",
        "tool_call": true,
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 2.5,
          "output": 10,
          "cache_read": 1.25
        }
      },
      "gpt-6-astra": {
        "name": "GPT-6 Astra",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 10,
          "output": 50,
          "cache_read": 1,
          "cache_write": 12.5,
          "tiers": [
            {
              "input": 20,
              "output": 75,
              "cache_read": 2,
              "cache_write": 25,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 20,
            "output": 75,
            "cache_read": 2,
            "cache_write": 25
          }
        }
      },
      "gpt-5.1": {
        "name": "GPT-5.1",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": true,
        "cost": {
          "input": 1.25,
          "output": 10,
          "cache_read": 0.125
        }
      },
      "gpt-4o-mini": {
        "name": "GPT-4o mini",
        "tool_call": true,
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 0.15,
          "output": 0.6,
          "cache_read": 0.075
        }
      },
      "o3-pro": {
        "name": "o3-pro",
        "tool_call": true,
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 20,
          "output": 80
        }
      },
      "gpt-daybreak-blue-latest": {
        "name": "Daybreak Blue",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 4,
          "output": 20,
          "cache_read": 0.4,
          "cache_write": 5,
          "tiers": [
            {
              "input": 8,
              "output": 30,
              "cache_read": 0.8,
              "cache_write": 10,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 8,
            "output": 30,
            "cache_read": 0.8,
            "cache_write": 10
          }
        }
      },
      "gpt-5.4-mini": {
        "name": "GPT-5.4 mini",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": true,
        "cost": {
          "input": 0.75,
          "output": 4.5,
          "cache_read": 0.075
        }
      },
      "gpt-5.6-luna": {
        "name": "GPT-5.6 Luna",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 0.2,
          "output": 1.2,
          "cache_read": 0.02,
          "cache_write": 0.25,
          "tiers": [
            {
              "input": 0.4,
              "output": 1.8,
              "cache_read": 0.04,
              "cache_write": 0.5,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 0.4,
            "output": 1.8,
            "cache_read": 0.04,
            "cache_write": 0.5
          }
        }
      },
      "gpt-5.2": {
        "name": "GPT-5.2",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": true,
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        }
      },
      "gpt-5.5": {
        "name": "GPT-5.5",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 5,
          "output": 30,
          "cache_read": 0.5,
          "tiers": [
            {
              "input": 10,
              "output": 45,
              "cache_read": 1,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 10,
            "output": 45,
            "cache_read": 1
          }
        }
      },
      "gpt-4.1": {
        "name": "GPT-4.1",
        "tool_call": true,
        "limit": {
          "context": 1047576,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 2,
          "output": 8,
          "cache_read": 0.5
        }
      },
      "gpt-4o-2024-11-20": {
        "name": "GPT-4o (2024-11-20)",
        "tool_call": true,
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 2.5,
          "output": 10,
          "cache_read": 1.25
        }
      },
      "gpt-4.1-mini": {
        "name": "GPT-4.1 mini",
        "tool_call": true,
        "limit": {
          "context": 1047576,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 0.4,
          "output": 1.6,
          "cache_read": 0.1
        }
      },
      "gpt-6-luna": {
        "name": "GPT-6 Luna",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 0.1,
          "output": 0.5,
          "cache_read": 0.01,
          "cache_write": 0.125,
          "tiers": [
            {
              "input": 0.2,
              "output": 0.75,
              "cache_read": 0.02,
              "cache_write": 0.25,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 0.2,
            "output": 0.75,
            "cache_read": 0.02,
            "cache_write": 0.25
          }
        }
      },
      "gpt-5.3-chat-latest": {
        "name": "GPT-5.3 Chat (latest)",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 1.75,
          "output": 14,
          "cache_read": 0.175
        }
      },
      "gpt-5.6-terra": {
        "name": "GPT-5.6 Terra",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 2,
          "output": 12,
          "cache_read": 0.2,
          "cache_write": 2.5,
          "tiers": [
            {
              "input": 4,
              "output": 18,
              "cache_read": 0.4,
              "cache_write": 5,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 4,
            "output": 18,
            "cache_read": 0.4,
            "cache_write": 5
          }
        }
      },
      "gpt-4-turbo": {
        "name": "GPT-4 Turbo",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "temperature": true,
        "cost": {
          "input": 10,
          "output": 30
        }
      },
      "gpt-daybreak-red-latest": {
        "name": "Daybreak Red",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 12.5,
          "output": 75,
          "cache_read": 1.25,
          "cache_write": 15.625
        }
      },
      "o3": {
        "name": "o3",
        "tool_call": true,
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 2,
          "output": 8,
          "cache_read": 0.5
        }
      },
      "gpt-5": {
        "name": "GPT-5",
        "tool_call": true,
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "minimal",
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 1.25,
          "output": 10,
          "cache_read": 0.125
        }
      },
      "gpt-5.6-sol": {
        "name": "GPT-5.6 Sol",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 4,
          "output": 20,
          "cache_read": 0.4,
          "cache_write": 5,
          "tiers": [
            {
              "input": 8,
              "output": 30,
              "cache_read": 0.8,
              "cache_write": 10,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 8,
            "output": 30,
            "cache_read": 0.8,
            "cache_write": 10
          }
        }
      },
      "gpt-6-sol": {
        "name": "GPT-6 Sol",
        "tool_call": true,
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "none",
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 2,
          "output": 10,
          "cache_read": 0.2,
          "cache_write": 2.5,
          "tiers": [
            {
              "input": 4,
              "output": 15,
              "cache_read": 0.4,
              "cache_write": 5,
              "tier": {
                "type": "context",
                "size": 272000
              }
            }
          ],
          "context_over_200k": {
            "input": 4,
            "output": 15,
            "cache_read": 0.4,
            "cache_write": 5
          }
        }
      },
      "o1-pro": {
        "name": "o1-pro",
        "tool_call": true,
        "status": "deprecated",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 150,
          "output": 600
        }
      }
    }
  },
  "anthropic": {
    "models": {
      "claude-haiku-4-5": {
        "name": "Claude Haiku 4.5 (latest)",
        "tool_call": true,
        "limit": {
          "context": 200000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "budget_tokens",
            "min": 1024
          }
        ],
        "temperature": true,
        "cost": {
          "input": 1,
          "output": 5,
          "cache_read": 0.1,
          "cache_write": 1.25
        }
      },
      "claude-opus-4-5": {
        "name": "Claude Opus 4.5 (latest)",
        "tool_call": true,
        "limit": {
          "context": 200000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high"
            ]
          },
          {
            "type": "budget_tokens",
            "min": 1024
          }
        ],
        "temperature": true,
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5,
          "cache_write": 6.25
        }
      },
      "claude-sonnet-4-5": {
        "name": "Claude Sonnet 4.5 (latest)",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "budget_tokens",
            "min": 1024
          }
        ],
        "temperature": true,
        "cost": {
          "input": 3,
          "output": 15,
          "cache_read": 0.3,
          "cache_write": 3.75
        }
      },
      "claude-opus-5-5": {
        "name": "Claude Opus 5.5",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 4,
          "output": 20,
          "cache_read": 0.2,
          "cache_write": 5
        }
      },
      "claude-fable-5-1": {
        "name": "Claude Fable 5.1",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 10,
          "output": 50,
          "cache_read": 0.25,
          "cache_write": 12.5
        }
      },
      "claude-opus-4-5-20251101": {
        "name": "Claude Opus 4.5",
        "tool_call": true,
        "limit": {
          "context": 200000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high"
            ]
          },
          {
            "type": "budget_tokens",
            "min": 1024
          }
        ],
        "temperature": true,
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5,
          "cache_write": 6.25
        }
      },
      "claude-opus-5": {
        "name": "Claude Opus 5",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5,
          "cache_write": 6.25
        }
      },
      "claude-fable-5": {
        "name": "Claude Fable 5",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 10,
          "output": 50,
          "cache_read": 1,
          "cache_write": 12.5
        }
      },
      "claude-opus-4-8": {
        "name": "Claude Opus 4.8",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5,
          "cache_write": 6.25
        }
      },
      "claude-sonnet-4-5-20250929": {
        "name": "Claude Sonnet 4.5",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "budget_tokens",
            "min": 1024
          }
        ],
        "temperature": true,
        "cost": {
          "input": 3,
          "output": 15,
          "cache_read": 0.3,
          "cache_write": 3.75
        }
      },
      "claude-sonnet-5": {
        "name": "Claude Sonnet 5",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "toggle"
          },
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 2,
          "output": 10,
          "cache_read": 0.2,
          "cache_write": 2.5
        }
      },
      "claude-opus-4-6": {
        "name": "Claude Opus 4.6",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "max"
            ]
          },
          {
            "type": "budget_tokens",
            "min": 1024
          }
        ],
        "temperature": true,
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5,
          "cache_write": 6.25
        }
      },
      "claude-haiku-4-5-20251001": {
        "name": "Claude Haiku 4.5",
        "tool_call": true,
        "limit": {
          "context": 200000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "budget_tokens",
            "min": 1024
          }
        ],
        "temperature": true,
        "cost": {
          "input": 1,
          "output": 5,
          "cache_read": 0.1,
          "cache_write": 1.25
        }
      },
      "claude-sonnet-4-6": {
        "name": "Claude Sonnet 4.6",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "max"
            ]
          },
          {
            "type": "budget_tokens",
            "min": 1024
          }
        ],
        "temperature": true,
        "cost": {
          "input": 3,
          "output": 15,
          "cache_read": 0.3,
          "cache_write": 3.75
        }
      },
      "claude-sonnet-5-5": {
        "name": "Claude Sonnet 5.5",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 2,
          "output": 10,
          "cache_read": 0.2,
          "cache_write": 2.5
        }
      },
      "claude-opus-4-7": {
        "name": "Claude Opus 4.7",
        "tool_call": true,
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "reasoning_options": [
          {
            "type": "effort",
            "values": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          }
        ],
        "temperature": false,
        "cost": {
          "input": 5,
          "output": 25,
          "cache_read": 0.5,
          "cache_write": 6.25
        }
      }
    }
  }
}
''';
